
name: Daily Scraper

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '8 16 * * *'

jobs:
  CISA-KEV:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scrape CISA KEV
      id: scraper
      run: curl --silent --output cisa_kev-download.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Compare changes
      id: check_diff
      run: |
        python3 json_diff.py 
        cat $GITHUB_OUTPUT  # Debug: Show contents of $GITHUB_OUTPUT
      continue-on-error: true

    - name: Debug exit code
      run: |
        echo "Exit code from check_diff step: ${{ steps.check_diff.outputs.exit_code }}"
        echo "Is exit_code non-zero? ${{ steps.check_diff.outputs.exit_code != '0' }}"

    - name: Check if any new JSON
      if: ${{ steps.check_diff.outputs.exit_code != '0' }}
      run: |
        echo "json_diff.py detected differences (exit code: ${{ steps.check_diff.outputs.exit_code }})"

    - name: Backup JSON
      if: ${{ steps.check_diff.outputs.exit_code != '0' }}
      run: |
        [ -f cisa_kev.json ] && mv cisa_kev.json cisa_kev-old.json || echo "No existing cisa_kev.json to backup"
        mv cisa_kev-download.json cisa_kev.json

    - name: Commit changes
      if: ${{ steps.check_diff.outputs.exit_code != '0' }}
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update JSON: ${timestamp}" || echo "No changes to commit"
        git push
