
name: CISA KEV Scraper

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '8 16 * * *'

jobs:
  Daily_Scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scrape CISA KEV
      id: scraper
      run: curl --silent --output cisa_kev-download.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

    - name: Compare changes
      id: check_diff
      run: |
        ls -l *.json
        python3 json_diff.py
        echo "exit_code=$?" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Check if any new JSON
      if: ${{ steps.check_diff.outputs.exit_code != '0' }}
      run: |
        echo "check_diff returned exit code: ${{ steps.check_diff.outputs.exit_code }}"

    - name: Backup JSON
      if: ${{ steps.check_diff.outputs.exit_code != '0' }}
      run: |
        mv cisa_kev.json cisa_kev-old.json
        mv cisa_kev-download.json cisa_kev.json

    - name: Commit changes
      if: ${{ steps.check_diff.outputs.exit_code != '0' }}
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update JSON: ${timestamp}" || exit 0
        git push

