name: Daily Scraper 

on:
  workflow_dispatch:
  schedule:
    - cron: '8 16 * * *'

jobs:
  CISA-KEV:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Backup JSON
      run: mv cisa_kev.json cisa_kev-old.json

    - name: Scrape CISA KEV
      run: curl --silent --output cisa_kev.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

    - name: Commit changes
      run: |-
        git config --local user.name "Automated"
        git config --local user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update JSON: ${timestamp}" || exit 0
        git push


